vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
	opencv-support DEPTHAI_OPENCV_SUPPORT
	pcl-support DEPTHAI_PCL_SUPPORT
	curl-support DEPTHAI_CURL_SUPPORT
	protobuf-support DEPTHAI_ENABLE_PROTOBUF
	python-bindings DEPTHAI_BUILD_PYTHON
	remote-connection-support DEPTHAI_ENABLE_REMOTE_CONNECTION
	rtabmap DEPTHAI_RTABMAP_SUPPORT
	apriltag DEPTHAI_ENABLE_APRIL_TAG
	backward DEPTHAI_ENABLE_BACKWARD
	basalt DEPTHAI_BASALT_SUPPORT
	tests DEPTHAI_BUILD_TESTS
)

vcpkg_cmake_configure(
    SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}"
    OPTIONS
		-DDEPTHAI_BUILD_PYTHON=OFF
		-DDEPTHAI_BUILD_EXAMPLES=OFF
		-DDEPTHAI_BUILD_TESTS=OFF
		${FEATURE_OPTIONS}
)

vcpkg_cmake_install()
