device: 10.0.255.224
resolution: 1280x800
fps: 30.0
host_streams: minimal
no_debug_outputs: false
view_mode: 0
viz_disp_min: 0
viz_disp_max: 3567
camera:
  auto_exposure: true
  ae_compensation: -3
  exposure_us: 3000
  iso: 100
  sharpness: 0
  luma_denoise: 2
gpustereo:
  maxDisparity: 128
  numPyramidLevels: 3
  downsampleMethod: 0
  prefilterMethod: 3
  blockMatchRadius: 3
  adaptiveSupportRangeSigma: 0.0
  prefilterBilateralSigmaSpatial: 2.0
  prefilterBilateralSigmaRange: 0.07999999821186066
  refinementRadius: 5
  refinementRadiusFull: 2
  subpixelBits: 5
  lrCheck: true
  lrCheckFast: true
  medianSize: 3
  minDisp: 0
  confidenceThreshold: 28
  useCostVolume: false
  costVolumeAggregation: 1
  boxAggregationRadius: 2
  bilateralSpatialSigma: 2.0
  bilateralRangeSigma: 0.07999999821186066
  bilateralAggregationRadius: 2
  costMethod: 3
  pathAggregation: 0
  sgmP1: 0.5
  sgmP2: 2.0
  sgmAdaptiveP2: true
  useFp16: true
  useQcomAcceleratedOps: true
  secondPeakThreshold: 0.0
  secondPeakMinDisparityGap: 0
  censusRadiusX: 2
  censusRadiusY: 2
  speckleMaxSize: 0
  speckleMaxDiff: 1
  speckleFilterBackend: 0
  textureFilterRadius: 0
  textureThreshold: 25.0
  featureMaskEdgeThresh: 0.0
  featureMaskCornerThresh: 0.0
  featureMaskMorphRadius: 1
  edgeAwareRadius: 0
  edgeAwareEps: 0.009999999776482582
  holeFillRadius: 1
  holeFillSigmaSpatial: 2.0
  holeFillSigmaRange: 0.05000000074505806
  temporalAlpha: 0.0
  temporalDelta: 0
  temporalPersistencyMode: 3
  regionRefine: false
  regionRefineCellSize: 16
  regionRefinePlaneResidualThresh: 3.0
  depthUnit: MILLIMETER
  customDepthUnitMultiplier: 1000.0
ir_dot_projector: 1.0
