// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/LocationFix.proto

#include "foxglove/LocationFix.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace foxglove {

inline constexpr LocationFix::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_covariance_{},
        frame_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{nullptr},
        latitude_{0},
        longitude_{0},
        altitude_{0},
        position_covariance_type_{static_cast< ::foxglove::LocationFix_PositionCovarianceType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR LocationFix::LocationFix(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LocationFixDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LocationFixDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LocationFixDefaultTypeInternal() {}
  union {
    LocationFix _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LocationFixDefaultTypeInternal _LocationFix_default_instance_;
}  // namespace foxglove
static ::_pb::Metadata file_level_metadata_foxglove_2fLocationFix_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_foxglove_2fLocationFix_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_foxglove_2fLocationFix_2eproto = nullptr;
const ::uint32_t TableStruct_foxglove_2fLocationFix_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::foxglove::LocationFix, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::foxglove::LocationFix, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::foxglove::LocationFix, _impl_.timestamp_),
    PROTOBUF_FIELD_OFFSET(::foxglove::LocationFix, _impl_.frame_id_),
    PROTOBUF_FIELD_OFFSET(::foxglove::LocationFix, _impl_.latitude_),
    PROTOBUF_FIELD_OFFSET(::foxglove::LocationFix, _impl_.longitude_),
    PROTOBUF_FIELD_OFFSET(::foxglove::LocationFix, _impl_.altitude_),
    PROTOBUF_FIELD_OFFSET(::foxglove::LocationFix, _impl_.position_covariance_),
    PROTOBUF_FIELD_OFFSET(::foxglove::LocationFix, _impl_.position_covariance_type_),
    0,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 15, -1, sizeof(::foxglove::LocationFix)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::foxglove::_LocationFix_default_instance_._instance,
};
const char descriptor_table_protodef_foxglove_2fLocationFix_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\032foxglove/LocationFix.proto\022\010foxglove\032\037"
    "google/protobuf/timestamp.proto\"\312\002\n\013Loca"
    "tionFix\022-\n\ttimestamp\030\006 \001(\0132\032.google.prot"
    "obuf.Timestamp\022\020\n\010frame_id\030\007 \001(\t\022\020\n\010lati"
    "tude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\022\020\n\010altitud"
    "e\030\003 \001(\001\022\033\n\023position_covariance\030\004 \003(\001\022N\n\030"
    "position_covariance_type\030\005 \001(\0162,.foxglov"
    "e.LocationFix.PositionCovarianceType\"V\n\026"
    "PositionCovarianceType\022\013\n\007UNKNOWN\020\000\022\020\n\014A"
    "PPROXIMATED\020\001\022\022\n\016DIAGONAL_KNOWN\020\002\022\t\n\005KNO"
    "WN\020\003b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_foxglove_2fLocationFix_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_foxglove_2fLocationFix_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_foxglove_2fLocationFix_2eproto = {
    false,
    false,
    412,
    descriptor_table_protodef_foxglove_2fLocationFix_2eproto,
    "foxglove/LocationFix.proto",
    &descriptor_table_foxglove_2fLocationFix_2eproto_once,
    descriptor_table_foxglove_2fLocationFix_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_foxglove_2fLocationFix_2eproto::offsets,
    file_level_metadata_foxglove_2fLocationFix_2eproto,
    file_level_enum_descriptors_foxglove_2fLocationFix_2eproto,
    file_level_service_descriptors_foxglove_2fLocationFix_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_foxglove_2fLocationFix_2eproto_getter() {
  return &descriptor_table_foxglove_2fLocationFix_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_foxglove_2fLocationFix_2eproto(&descriptor_table_foxglove_2fLocationFix_2eproto);
namespace foxglove {
const ::google::protobuf::EnumDescriptor* LocationFix_PositionCovarianceType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_foxglove_2fLocationFix_2eproto);
  return file_level_enum_descriptors_foxglove_2fLocationFix_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t LocationFix_PositionCovarianceType_internal_data_[] = {
    262144u, 0u, };
bool LocationFix_PositionCovarianceType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr LocationFix_PositionCovarianceType LocationFix::UNKNOWN;
constexpr LocationFix_PositionCovarianceType LocationFix::APPROXIMATED;
constexpr LocationFix_PositionCovarianceType LocationFix::DIAGONAL_KNOWN;
constexpr LocationFix_PositionCovarianceType LocationFix::KNOWN;
constexpr LocationFix_PositionCovarianceType LocationFix::PositionCovarianceType_MIN;
constexpr LocationFix_PositionCovarianceType LocationFix::PositionCovarianceType_MAX;
constexpr int LocationFix::PositionCovarianceType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class LocationFix::_Internal {
 public:
  using HasBits = decltype(std::declval<LocationFix>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(LocationFix, _impl_._has_bits_);
  static const ::google::protobuf::Timestamp& timestamp(const LocationFix* msg);
  static void set_has_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::protobuf::Timestamp& LocationFix::_Internal::timestamp(const LocationFix* msg) {
  return *msg->_impl_.timestamp_;
}
void LocationFix::clear_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
LocationFix::LocationFix(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:foxglove.LocationFix)
}
inline PROTOBUF_NDEBUG_INLINE LocationFix::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        position_covariance_{visibility, arena, from.position_covariance_},
        frame_id_(arena, from.frame_id_) {}

LocationFix::LocationFix(
    ::google::protobuf::Arena* arena,
    const LocationFix& from)
    : ::google::protobuf::Message(arena) {
  LocationFix* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.timestamp_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::protobuf::Timestamp>(arena, *from._impl_.timestamp_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, latitude_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, latitude_),
           offsetof(Impl_, position_covariance_type_) -
               offsetof(Impl_, latitude_) +
               sizeof(Impl_::position_covariance_type_));

  // @@protoc_insertion_point(copy_constructor:foxglove.LocationFix)
}
inline PROTOBUF_NDEBUG_INLINE LocationFix::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        position_covariance_{visibility, arena},
        frame_id_(arena) {}

inline void LocationFix::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, position_covariance_type_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::position_covariance_type_));
}
LocationFix::~LocationFix() {
  // @@protoc_insertion_point(destructor:foxglove.LocationFix)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LocationFix::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.frame_id_.Destroy();
  delete _impl_.timestamp_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LocationFix::Clear() {
// @@protoc_insertion_point(message_clear_start:foxglove.LocationFix)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.position_covariance_.Clear();
  _impl_.frame_id_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.timestamp_ != nullptr);
    _impl_.timestamp_->Clear();
  }
  ::memset(&_impl_.latitude_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.position_covariance_type_) -
      reinterpret_cast<char*>(&_impl_.latitude_)) + sizeof(_impl_.position_covariance_type_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LocationFix::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 1, 37, 2> LocationFix::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LocationFix, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_LocationFix_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double latitude = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.latitude_)}},
    // double longitude = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.longitude_)}},
    // double altitude = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.altitude_)}},
    // repeated double position_covariance = 4;
    {::_pbi::TcParser::FastF64P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.position_covariance_)}},
    // .foxglove.LocationFix.PositionCovarianceType position_covariance_type = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LocationFix, _impl_.position_covariance_type_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.position_covariance_type_)}},
    // .google.protobuf.Timestamp timestamp = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 0, 0, PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.timestamp_)}},
    // string frame_id = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.frame_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double latitude = 1;
    {PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.latitude_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double longitude = 2;
    {PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.longitude_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double altitude = 3;
    {PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.altitude_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // repeated double position_covariance = 4;
    {PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.position_covariance_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // .foxglove.LocationFix.PositionCovarianceType position_covariance_type = 5;
    {PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.position_covariance_type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .google.protobuf.Timestamp timestamp = 6;
    {PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string frame_id = 7;
    {PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.frame_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }}, {{
    "\24\0\0\0\0\0\0\10"
    "foxglove.LocationFix"
    "frame_id"
  }},
};

::uint8_t* LocationFix::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:foxglove.LocationFix)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // double latitude = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_latitude = this->_internal_latitude();
  ::uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        1, this->_internal_latitude(), target);
  }

  // double longitude = 2;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_longitude = this->_internal_longitude();
  ::uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this->_internal_longitude(), target);
  }

  // double altitude = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_altitude = this->_internal_altitude();
  ::uint64_t raw_altitude;
  memcpy(&raw_altitude, &tmp_altitude, sizeof(tmp_altitude));
  if (raw_altitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this->_internal_altitude(), target);
  }

  // repeated double position_covariance = 4;
  if (this->_internal_position_covariance_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_position_covariance(), target);
  }

  // .foxglove.LocationFix.PositionCovarianceType position_covariance_type = 5;
  if (this->_internal_position_covariance_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        5, this->_internal_position_covariance_type(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Timestamp timestamp = 6;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  // string frame_id = 7;
  if (!this->_internal_frame_id().empty()) {
    const std::string& _s = this->_internal_frame_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "foxglove.LocationFix.frame_id");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foxglove.LocationFix)
  return target;
}

::size_t LocationFix::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foxglove.LocationFix)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double position_covariance = 4;
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_position_covariance_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // string frame_id = 7;
  if (!this->_internal_frame_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_frame_id());
  }

  // .google.protobuf.Timestamp timestamp = 6;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.timestamp_);
  }

  // double latitude = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_latitude = this->_internal_latitude();
  ::uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    total_size += 9;
  }

  // double longitude = 2;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_longitude = this->_internal_longitude();
  ::uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    total_size += 9;
  }

  // double altitude = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_altitude = this->_internal_altitude();
  ::uint64_t raw_altitude;
  memcpy(&raw_altitude, &tmp_altitude, sizeof(tmp_altitude));
  if (raw_altitude != 0) {
    total_size += 9;
  }

  // .foxglove.LocationFix.PositionCovarianceType position_covariance_type = 5;
  if (this->_internal_position_covariance_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_position_covariance_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LocationFix::_class_data_ = {
    LocationFix::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LocationFix::GetClassData() const {
  return &_class_data_;
}

void LocationFix::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LocationFix*>(&to_msg);
  auto& from = static_cast<const LocationFix&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:foxglove.LocationFix)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_position_covariance()->MergeFrom(from._internal_position_covariance());
  if (!from._internal_frame_id().empty()) {
    _this->_internal_set_frame_id(from._internal_frame_id());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_timestamp()->::google::protobuf::Timestamp::MergeFrom(
        from._internal_timestamp());
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_latitude = from._internal_latitude();
  ::uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    _this->_internal_set_latitude(from._internal_latitude());
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_longitude = from._internal_longitude();
  ::uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    _this->_internal_set_longitude(from._internal_longitude());
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_altitude = from._internal_altitude();
  ::uint64_t raw_altitude;
  memcpy(&raw_altitude, &tmp_altitude, sizeof(tmp_altitude));
  if (raw_altitude != 0) {
    _this->_internal_set_altitude(from._internal_altitude());
  }
  if (from._internal_position_covariance_type() != 0) {
    _this->_internal_set_position_covariance_type(from._internal_position_covariance_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LocationFix::CopyFrom(const LocationFix& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foxglove.LocationFix)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LocationFix::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LocationFix::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LocationFix::InternalSwap(LocationFix* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.position_covariance_.InternalSwap(&other->_impl_.position_covariance_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.frame_id_, &other->_impl_.frame_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.position_covariance_type_)
      + sizeof(LocationFix::_impl_.position_covariance_type_)
      - PROTOBUF_FIELD_OFFSET(LocationFix, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata LocationFix::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_foxglove_2fLocationFix_2eproto_getter, &descriptor_table_foxglove_2fLocationFix_2eproto_once,
      file_level_metadata_foxglove_2fLocationFix_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace foxglove
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
