// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/TextPrimitive.proto

#include "foxglove/TextPrimitive.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace foxglove {

inline constexpr TextPrimitive::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pose_{nullptr},
        color_{nullptr},
        font_size_{0},
        billboard_{false},
        scale_invariant_{false} {}

template <typename>
PROTOBUF_CONSTEXPR TextPrimitive::TextPrimitive(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TextPrimitiveDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TextPrimitiveDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TextPrimitiveDefaultTypeInternal() {}
  union {
    TextPrimitive _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TextPrimitiveDefaultTypeInternal _TextPrimitive_default_instance_;
}  // namespace foxglove
static ::_pb::Metadata file_level_metadata_foxglove_2fTextPrimitive_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_foxglove_2fTextPrimitive_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_foxglove_2fTextPrimitive_2eproto = nullptr;
const ::uint32_t TableStruct_foxglove_2fTextPrimitive_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::foxglove::TextPrimitive, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::foxglove::TextPrimitive, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::foxglove::TextPrimitive, _impl_.pose_),
    PROTOBUF_FIELD_OFFSET(::foxglove::TextPrimitive, _impl_.billboard_),
    PROTOBUF_FIELD_OFFSET(::foxglove::TextPrimitive, _impl_.font_size_),
    PROTOBUF_FIELD_OFFSET(::foxglove::TextPrimitive, _impl_.scale_invariant_),
    PROTOBUF_FIELD_OFFSET(::foxglove::TextPrimitive, _impl_.color_),
    PROTOBUF_FIELD_OFFSET(::foxglove::TextPrimitive, _impl_.text_),
    0,
    ~0u,
    ~0u,
    ~0u,
    1,
    ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 14, -1, sizeof(::foxglove::TextPrimitive)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::foxglove::_TextPrimitive_default_instance_._instance,
};
const char descriptor_table_protodef_foxglove_2fTextPrimitive_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\034foxglove/TextPrimitive.proto\022\010foxglove"
    "\032\024foxglove/Color.proto\032\023foxglove/Pose.pr"
    "oto\"\232\001\n\rTextPrimitive\022\034\n\004pose\030\001 \001(\0132\016.fo"
    "xglove.Pose\022\021\n\tbillboard\030\002 \001(\010\022\021\n\tfont_s"
    "ize\030\003 \001(\001\022\027\n\017scale_invariant\030\004 \001(\010\022\036\n\005co"
    "lor\030\005 \001(\0132\017.foxglove.Color\022\014\n\004text\030\006 \001(\t"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_foxglove_2fTextPrimitive_2eproto_deps[2] =
    {
        &::descriptor_table_foxglove_2fColor_2eproto,
        &::descriptor_table_foxglove_2fPose_2eproto,
};
static ::absl::once_flag descriptor_table_foxglove_2fTextPrimitive_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_foxglove_2fTextPrimitive_2eproto = {
    false,
    false,
    248,
    descriptor_table_protodef_foxglove_2fTextPrimitive_2eproto,
    "foxglove/TextPrimitive.proto",
    &descriptor_table_foxglove_2fTextPrimitive_2eproto_once,
    descriptor_table_foxglove_2fTextPrimitive_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_foxglove_2fTextPrimitive_2eproto::offsets,
    file_level_metadata_foxglove_2fTextPrimitive_2eproto,
    file_level_enum_descriptors_foxglove_2fTextPrimitive_2eproto,
    file_level_service_descriptors_foxglove_2fTextPrimitive_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_foxglove_2fTextPrimitive_2eproto_getter() {
  return &descriptor_table_foxglove_2fTextPrimitive_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_foxglove_2fTextPrimitive_2eproto(&descriptor_table_foxglove_2fTextPrimitive_2eproto);
namespace foxglove {
// ===================================================================

class TextPrimitive::_Internal {
 public:
  using HasBits = decltype(std::declval<TextPrimitive>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_._has_bits_);
  static const ::foxglove::Pose& pose(const TextPrimitive* msg);
  static void set_has_pose(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::foxglove::Color& color(const TextPrimitive* msg);
  static void set_has_color(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::foxglove::Pose& TextPrimitive::_Internal::pose(const TextPrimitive* msg) {
  return *msg->_impl_.pose_;
}
const ::foxglove::Color& TextPrimitive::_Internal::color(const TextPrimitive* msg) {
  return *msg->_impl_.color_;
}
void TextPrimitive::clear_pose() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.pose_ != nullptr) _impl_.pose_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void TextPrimitive::clear_color() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.color_ != nullptr) _impl_.color_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
TextPrimitive::TextPrimitive(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:foxglove.TextPrimitive)
}
inline PROTOBUF_NDEBUG_INLINE TextPrimitive::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        text_(arena, from.text_) {}

TextPrimitive::TextPrimitive(
    ::google::protobuf::Arena* arena,
    const TextPrimitive& from)
    : ::google::protobuf::Message(arena) {
  TextPrimitive* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.pose_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::foxglove::Pose>(arena, *from._impl_.pose_)
                : nullptr;
  _impl_.color_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::foxglove::Color>(arena, *from._impl_.color_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, font_size_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, font_size_),
           offsetof(Impl_, scale_invariant_) -
               offsetof(Impl_, font_size_) +
               sizeof(Impl_::scale_invariant_));

  // @@protoc_insertion_point(copy_constructor:foxglove.TextPrimitive)
}
inline PROTOBUF_NDEBUG_INLINE TextPrimitive::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        text_(arena) {}

inline void TextPrimitive::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pose_),
           0,
           offsetof(Impl_, scale_invariant_) -
               offsetof(Impl_, pose_) +
               sizeof(Impl_::scale_invariant_));
}
TextPrimitive::~TextPrimitive() {
  // @@protoc_insertion_point(destructor:foxglove.TextPrimitive)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TextPrimitive::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.text_.Destroy();
  delete _impl_.pose_;
  delete _impl_.color_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void TextPrimitive::Clear() {
// @@protoc_insertion_point(message_clear_start:foxglove.TextPrimitive)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.text_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.pose_ != nullptr);
      _impl_.pose_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.color_ != nullptr);
      _impl_.color_->Clear();
    }
  }
  ::memset(&_impl_.font_size_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.scale_invariant_) -
      reinterpret_cast<char*>(&_impl_.font_size_)) + sizeof(_impl_.scale_invariant_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* TextPrimitive::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 2, 35, 2> TextPrimitive::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_TextPrimitive_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .foxglove.Pose pose = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.pose_)}},
    // bool billboard = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TextPrimitive, _impl_.billboard_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.billboard_)}},
    // double font_size = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.font_size_)}},
    // bool scale_invariant = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TextPrimitive, _impl_.scale_invariant_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.scale_invariant_)}},
    // .foxglove.Color color = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 1, 1, PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.color_)}},
    // string text = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.text_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .foxglove.Pose pose = 1;
    {PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.pose_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool billboard = 2;
    {PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.billboard_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // double font_size = 3;
    {PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.font_size_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // bool scale_invariant = 4;
    {PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.scale_invariant_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // .foxglove.Color color = 5;
    {PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.color_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string text = 6;
    {PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.text_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::foxglove::Pose>()},
    {::_pbi::TcParser::GetTable<::foxglove::Color>()},
  }}, {{
    "\26\0\0\0\0\0\4\0"
    "foxglove.TextPrimitive"
    "text"
  }},
};

::uint8_t* TextPrimitive::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:foxglove.TextPrimitive)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .foxglove.Pose pose = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, _Internal::pose(this),
        _Internal::pose(this).GetCachedSize(), target, stream);
  }

  // bool billboard = 2;
  if (this->_internal_billboard() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_billboard(), target);
  }

  // double font_size = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_font_size = this->_internal_font_size();
  ::uint64_t raw_font_size;
  memcpy(&raw_font_size, &tmp_font_size, sizeof(tmp_font_size));
  if (raw_font_size != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this->_internal_font_size(), target);
  }

  // bool scale_invariant = 4;
  if (this->_internal_scale_invariant() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this->_internal_scale_invariant(), target);
  }

  // .foxglove.Color color = 5;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, _Internal::color(this),
        _Internal::color(this).GetCachedSize(), target, stream);
  }

  // string text = 6;
  if (!this->_internal_text().empty()) {
    const std::string& _s = this->_internal_text();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "foxglove.TextPrimitive.text");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foxglove.TextPrimitive)
  return target;
}

::size_t TextPrimitive::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foxglove.TextPrimitive)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string text = 6;
  if (!this->_internal_text().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_text());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .foxglove.Pose pose = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.pose_);
    }

    // .foxglove.Color color = 5;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.color_);
    }

  }
  // double font_size = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_font_size = this->_internal_font_size();
  ::uint64_t raw_font_size;
  memcpy(&raw_font_size, &tmp_font_size, sizeof(tmp_font_size));
  if (raw_font_size != 0) {
    total_size += 9;
  }

  // bool billboard = 2;
  if (this->_internal_billboard() != 0) {
    total_size += 2;
  }

  // bool scale_invariant = 4;
  if (this->_internal_scale_invariant() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData TextPrimitive::_class_data_ = {
    TextPrimitive::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* TextPrimitive::GetClassData() const {
  return &_class_data_;
}

void TextPrimitive::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<TextPrimitive*>(&to_msg);
  auto& from = static_cast<const TextPrimitive&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:foxglove.TextPrimitive)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_pose()->::foxglove::Pose::MergeFrom(
          from._internal_pose());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_color()->::foxglove::Color::MergeFrom(
          from._internal_color());
    }
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_font_size = from._internal_font_size();
  ::uint64_t raw_font_size;
  memcpy(&raw_font_size, &tmp_font_size, sizeof(tmp_font_size));
  if (raw_font_size != 0) {
    _this->_internal_set_font_size(from._internal_font_size());
  }
  if (from._internal_billboard() != 0) {
    _this->_internal_set_billboard(from._internal_billboard());
  }
  if (from._internal_scale_invariant() != 0) {
    _this->_internal_set_scale_invariant(from._internal_scale_invariant());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TextPrimitive::CopyFrom(const TextPrimitive& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foxglove.TextPrimitive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool TextPrimitive::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* TextPrimitive::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void TextPrimitive::InternalSwap(TextPrimitive* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.scale_invariant_)
      + sizeof(TextPrimitive::_impl_.scale_invariant_)
      - PROTOBUF_FIELD_OFFSET(TextPrimitive, _impl_.pose_)>(
          reinterpret_cast<char*>(&_impl_.pose_),
          reinterpret_cast<char*>(&other->_impl_.pose_));
}

::google::protobuf::Metadata TextPrimitive::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_foxglove_2fTextPrimitive_2eproto_getter, &descriptor_table_foxglove_2fTextPrimitive_2eproto_once,
      file_level_metadata_foxglove_2fTextPrimitive_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace foxglove
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
