#!/usr/bin/env python3
import argparse
import ast
from pathlib import Path


ROOT_BASES = {"HostNode", "ThreadedHostNode", "BaseHostNode", "BaseThreadedHostNode", "BaseParser"}


def base_name(base: ast.expr) -> str | None:
    if isinstance(base, ast.Name):
        return base.id
    if isinstance(base, ast.Attribute):
        return base.attr
    if isinstance(base, ast.Subscript):
        return base_name(base.value)
    return None


def collect_classes(node_dir: Path) -> dict[str, set[str]]:
    classes: dict[str, set[str]] = {}
    for path in sorted(node_dir.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                classes[node.name] = {name for base in node.bases if (name := base_name(base)) is not None}
    return classes


def is_depthai_node(class_name: str, classes: dict[str, set[str]], visiting: set[str] | None = None) -> bool:
    if visiting is None:
        visiting = set()
    if class_name in visiting:
        return False
    visiting.add(class_name)

    bases = classes.get(class_name, set())
    if bases & ROOT_BASES:
        return True
    return any(base in classes and is_depthai_node(base, classes, visiting) for base in bases)


def write_header(names: list[str], output: Path) -> None:
    values = "\n".join(f'    "{name}",' for name in names)
    output.write_text(
        f"""#pragma once

#include <string>
#include <vector>

namespace dai::utility {{

// Generated by scripts/generate_depthai_nodes_names.py.
inline const std::vector<std::string> depthaiNodesNames = {{
{values}
}};

}}  // namespace dai::utility
""",
        encoding="utf-8",
    )


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Generate the depthai-nodes telemetry whitelist header.")
    parser.add_argument(
        "--depthai-nodes-root",
        type=Path,
        default=repo_root.parent / "depthai-nodes",
        help="Path to the depthai-nodes repository.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=repo_root / "src" / "utility" / "depthai_nodes_names.hpp",
        help="Header path to write.",
    )
    args = parser.parse_args()

    node_dir = args.depthai_nodes_root / "depthai_nodes" / "node"
    if not node_dir.exists():
        raise FileNotFoundError(f"depthai-nodes node directory not found: {node_dir}")

    classes = collect_classes(node_dir)
    names = sorted(name for name in classes if is_depthai_node(name, classes))
    write_header(names, args.output)
    print(f"Wrote {len(names)} depthai-nodes names to {args.output}")


if __name__ == "__main__":
    main()
