// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: daischemas/CircleAnnotation.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_daischemas_2fCircleAnnotation_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_daischemas_2fCircleAnnotation_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "daischemas/Color.pb.h"
#include "daischemas/Point2.pb.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_daischemas_2fCircleAnnotation_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_daischemas_2fCircleAnnotation_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_daischemas_2fCircleAnnotation_2eproto;
namespace dai {
namespace schemas {
class CircleAnnotation;
struct CircleAnnotationDefaultTypeInternal;
extern CircleAnnotationDefaultTypeInternal _CircleAnnotation_default_instance_;
}  // namespace schemas
}  // namespace dai
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace dai {
namespace schemas {

// ===================================================================


// -------------------------------------------------------------------

class CircleAnnotation final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dai.schemas.CircleAnnotation) */ {
 public:
  inline CircleAnnotation() : CircleAnnotation(nullptr) {}
  ~CircleAnnotation() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CircleAnnotation(::google::protobuf::internal::ConstantInitialized);

  inline CircleAnnotation(const CircleAnnotation& from)
      : CircleAnnotation(nullptr, from) {}
  CircleAnnotation(CircleAnnotation&& from) noexcept
    : CircleAnnotation() {
    *this = ::std::move(from);
  }

  inline CircleAnnotation& operator=(const CircleAnnotation& from) {
    CopyFrom(from);
    return *this;
  }
  inline CircleAnnotation& operator=(CircleAnnotation&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CircleAnnotation& default_instance() {
    return *internal_default_instance();
  }
  static inline const CircleAnnotation* internal_default_instance() {
    return reinterpret_cast<const CircleAnnotation*>(
               &_CircleAnnotation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CircleAnnotation& a, CircleAnnotation& b) {
    a.Swap(&b);
  }
  inline void Swap(CircleAnnotation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CircleAnnotation* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CircleAnnotation* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CircleAnnotation>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CircleAnnotation& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CircleAnnotation& from) {
    CircleAnnotation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(CircleAnnotation* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "dai.schemas.CircleAnnotation";
  }
  protected:
  explicit CircleAnnotation(::google::protobuf::Arena* arena);
  CircleAnnotation(::google::protobuf::Arena* arena, const CircleAnnotation& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 1,
    kPositionFieldNumber = 2,
    kFillColorFieldNumber = 5,
    kOutlineColorFieldNumber = 6,
    kDiameterFieldNumber = 3,
    kThicknessFieldNumber = 4,
  };
  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::google::protobuf::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::google::protobuf::Timestamp* release_timestamp();
  ::google::protobuf::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* value);
  void unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* value);
  ::google::protobuf::Timestamp* unsafe_arena_release_timestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  ::google::protobuf::Timestamp* _internal_mutable_timestamp();

  public:
  // .dai.schemas.Point2 position = 2;
  bool has_position() const;
  void clear_position() ;
  const ::dai::schemas::Point2& position() const;
  PROTOBUF_NODISCARD ::dai::schemas::Point2* release_position();
  ::dai::schemas::Point2* mutable_position();
  void set_allocated_position(::dai::schemas::Point2* value);
  void unsafe_arena_set_allocated_position(::dai::schemas::Point2* value);
  ::dai::schemas::Point2* unsafe_arena_release_position();

  private:
  const ::dai::schemas::Point2& _internal_position() const;
  ::dai::schemas::Point2* _internal_mutable_position();

  public:
  // .dai.schemas.Color fill_color = 5;
  bool has_fill_color() const;
  void clear_fill_color() ;
  const ::dai::schemas::Color& fill_color() const;
  PROTOBUF_NODISCARD ::dai::schemas::Color* release_fill_color();
  ::dai::schemas::Color* mutable_fill_color();
  void set_allocated_fill_color(::dai::schemas::Color* value);
  void unsafe_arena_set_allocated_fill_color(::dai::schemas::Color* value);
  ::dai::schemas::Color* unsafe_arena_release_fill_color();

  private:
  const ::dai::schemas::Color& _internal_fill_color() const;
  ::dai::schemas::Color* _internal_mutable_fill_color();

  public:
  // .dai.schemas.Color outline_color = 6;
  bool has_outline_color() const;
  void clear_outline_color() ;
  const ::dai::schemas::Color& outline_color() const;
  PROTOBUF_NODISCARD ::dai::schemas::Color* release_outline_color();
  ::dai::schemas::Color* mutable_outline_color();
  void set_allocated_outline_color(::dai::schemas::Color* value);
  void unsafe_arena_set_allocated_outline_color(::dai::schemas::Color* value);
  ::dai::schemas::Color* unsafe_arena_release_outline_color();

  private:
  const ::dai::schemas::Color& _internal_outline_color() const;
  ::dai::schemas::Color* _internal_mutable_outline_color();

  public:
  // double diameter = 3;
  void clear_diameter() ;
  double diameter() const;
  void set_diameter(double value);

  private:
  double _internal_diameter() const;
  void _internal_set_diameter(double value);

  public:
  // double thickness = 4;
  void clear_thickness() ;
  double thickness() const;
  void set_thickness(double value);

  private:
  double _internal_thickness() const;
  void _internal_set_thickness(double value);

  public:
  // @@protoc_insertion_point(class_scope:dai.schemas.CircleAnnotation)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 4,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::Timestamp* timestamp_;
    ::dai::schemas::Point2* position_;
    ::dai::schemas::Color* fill_color_;
    ::dai::schemas::Color* outline_color_;
    double diameter_;
    double thickness_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_daischemas_2fCircleAnnotation_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CircleAnnotation

// .google.protobuf.Timestamp timestamp = 1;
inline bool CircleAnnotation::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& CircleAnnotation::_internal_timestamp() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::google::protobuf::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& CircleAnnotation::timestamp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dai.schemas.CircleAnnotation.timestamp)
  return _internal_timestamp();
}
inline void CircleAnnotation::unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dai.schemas.CircleAnnotation.timestamp)
}
inline ::google::protobuf::Timestamp* CircleAnnotation::release_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* released = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::Timestamp* CircleAnnotation::unsafe_arena_release_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:dai.schemas.CircleAnnotation.timestamp)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* CircleAnnotation::_internal_mutable_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::Timestamp>(GetArena());
    _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.timestamp_;
}
inline ::google::protobuf::Timestamp* CircleAnnotation::mutable_timestamp() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:dai.schemas.CircleAnnotation.timestamp)
  return _msg;
}
inline void CircleAnnotation::set_allocated_timestamp(::google::protobuf::Timestamp* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:dai.schemas.CircleAnnotation.timestamp)
}

// .dai.schemas.Point2 position = 2;
inline bool CircleAnnotation::has_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.position_ != nullptr);
  return value;
}
inline const ::dai::schemas::Point2& CircleAnnotation::_internal_position() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::dai::schemas::Point2* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::dai::schemas::Point2&>(::dai::schemas::_Point2_default_instance_);
}
inline const ::dai::schemas::Point2& CircleAnnotation::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dai.schemas.CircleAnnotation.position)
  return _internal_position();
}
inline void CircleAnnotation::unsafe_arena_set_allocated_position(::dai::schemas::Point2* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = reinterpret_cast<::dai::schemas::Point2*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dai.schemas.CircleAnnotation.position)
}
inline ::dai::schemas::Point2* CircleAnnotation::release_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::dai::schemas::Point2* released = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::dai::schemas::Point2* CircleAnnotation::unsafe_arena_release_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:dai.schemas.CircleAnnotation.position)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::dai::schemas::Point2* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::dai::schemas::Point2* CircleAnnotation::_internal_mutable_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::dai::schemas::Point2>(GetArena());
    _impl_.position_ = reinterpret_cast<::dai::schemas::Point2*>(p);
  }
  return _impl_.position_;
}
inline ::dai::schemas::Point2* CircleAnnotation::mutable_position() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::dai::schemas::Point2* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:dai.schemas.CircleAnnotation.position)
  return _msg;
}
inline void CircleAnnotation::set_allocated_position(::dai::schemas::Point2* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.position_ = reinterpret_cast<::dai::schemas::Point2*>(value);
  // @@protoc_insertion_point(field_set_allocated:dai.schemas.CircleAnnotation.position)
}

// double diameter = 3;
inline void CircleAnnotation::clear_diameter() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.diameter_ = 0;
}
inline double CircleAnnotation::diameter() const {
  // @@protoc_insertion_point(field_get:dai.schemas.CircleAnnotation.diameter)
  return _internal_diameter();
}
inline void CircleAnnotation::set_diameter(double value) {
  _internal_set_diameter(value);
  // @@protoc_insertion_point(field_set:dai.schemas.CircleAnnotation.diameter)
}
inline double CircleAnnotation::_internal_diameter() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.diameter_;
}
inline void CircleAnnotation::_internal_set_diameter(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.diameter_ = value;
}

// double thickness = 4;
inline void CircleAnnotation::clear_thickness() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.thickness_ = 0;
}
inline double CircleAnnotation::thickness() const {
  // @@protoc_insertion_point(field_get:dai.schemas.CircleAnnotation.thickness)
  return _internal_thickness();
}
inline void CircleAnnotation::set_thickness(double value) {
  _internal_set_thickness(value);
  // @@protoc_insertion_point(field_set:dai.schemas.CircleAnnotation.thickness)
}
inline double CircleAnnotation::_internal_thickness() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.thickness_;
}
inline void CircleAnnotation::_internal_set_thickness(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.thickness_ = value;
}

// .dai.schemas.Color fill_color = 5;
inline bool CircleAnnotation::has_fill_color() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.fill_color_ != nullptr);
  return value;
}
inline const ::dai::schemas::Color& CircleAnnotation::_internal_fill_color() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::dai::schemas::Color* p = _impl_.fill_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::dai::schemas::Color&>(::dai::schemas::_Color_default_instance_);
}
inline const ::dai::schemas::Color& CircleAnnotation::fill_color() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dai.schemas.CircleAnnotation.fill_color)
  return _internal_fill_color();
}
inline void CircleAnnotation::unsafe_arena_set_allocated_fill_color(::dai::schemas::Color* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.fill_color_);
  }
  _impl_.fill_color_ = reinterpret_cast<::dai::schemas::Color*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dai.schemas.CircleAnnotation.fill_color)
}
inline ::dai::schemas::Color* CircleAnnotation::release_fill_color() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::dai::schemas::Color* released = _impl_.fill_color_;
  _impl_.fill_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::dai::schemas::Color* CircleAnnotation::unsafe_arena_release_fill_color() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:dai.schemas.CircleAnnotation.fill_color)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::dai::schemas::Color* temp = _impl_.fill_color_;
  _impl_.fill_color_ = nullptr;
  return temp;
}
inline ::dai::schemas::Color* CircleAnnotation::_internal_mutable_fill_color() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.fill_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::dai::schemas::Color>(GetArena());
    _impl_.fill_color_ = reinterpret_cast<::dai::schemas::Color*>(p);
  }
  return _impl_.fill_color_;
}
inline ::dai::schemas::Color* CircleAnnotation::mutable_fill_color() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::dai::schemas::Color* _msg = _internal_mutable_fill_color();
  // @@protoc_insertion_point(field_mutable:dai.schemas.CircleAnnotation.fill_color)
  return _msg;
}
inline void CircleAnnotation::set_allocated_fill_color(::dai::schemas::Color* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.fill_color_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.fill_color_ = reinterpret_cast<::dai::schemas::Color*>(value);
  // @@protoc_insertion_point(field_set_allocated:dai.schemas.CircleAnnotation.fill_color)
}

// .dai.schemas.Color outline_color = 6;
inline bool CircleAnnotation::has_outline_color() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.outline_color_ != nullptr);
  return value;
}
inline const ::dai::schemas::Color& CircleAnnotation::_internal_outline_color() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::dai::schemas::Color* p = _impl_.outline_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::dai::schemas::Color&>(::dai::schemas::_Color_default_instance_);
}
inline const ::dai::schemas::Color& CircleAnnotation::outline_color() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dai.schemas.CircleAnnotation.outline_color)
  return _internal_outline_color();
}
inline void CircleAnnotation::unsafe_arena_set_allocated_outline_color(::dai::schemas::Color* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.outline_color_);
  }
  _impl_.outline_color_ = reinterpret_cast<::dai::schemas::Color*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dai.schemas.CircleAnnotation.outline_color)
}
inline ::dai::schemas::Color* CircleAnnotation::release_outline_color() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::dai::schemas::Color* released = _impl_.outline_color_;
  _impl_.outline_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::dai::schemas::Color* CircleAnnotation::unsafe_arena_release_outline_color() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:dai.schemas.CircleAnnotation.outline_color)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::dai::schemas::Color* temp = _impl_.outline_color_;
  _impl_.outline_color_ = nullptr;
  return temp;
}
inline ::dai::schemas::Color* CircleAnnotation::_internal_mutable_outline_color() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  if (_impl_.outline_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::dai::schemas::Color>(GetArena());
    _impl_.outline_color_ = reinterpret_cast<::dai::schemas::Color*>(p);
  }
  return _impl_.outline_color_;
}
inline ::dai::schemas::Color* CircleAnnotation::mutable_outline_color() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::dai::schemas::Color* _msg = _internal_mutable_outline_color();
  // @@protoc_insertion_point(field_mutable:dai.schemas.CircleAnnotation.outline_color)
  return _msg;
}
inline void CircleAnnotation::set_allocated_outline_color(::dai::schemas::Color* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.outline_color_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.outline_color_ = reinterpret_cast<::dai::schemas::Color*>(value);
  // @@protoc_insertion_point(field_set_allocated:dai.schemas.CircleAnnotation.outline_color)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace schemas
}  // namespace dai


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_daischemas_2fCircleAnnotation_2eproto_2epb_2eh
