// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: daischemas/FrameTransform.proto

#include "daischemas/FrameTransform.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace dai {
namespace schemas {

inline constexpr FrameTransform::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        parent_frame_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        child_frame_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{nullptr},
        translation_{nullptr},
        rotation_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR FrameTransform::FrameTransform(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FrameTransformDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FrameTransformDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FrameTransformDefaultTypeInternal() {}
  union {
    FrameTransform _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FrameTransformDefaultTypeInternal _FrameTransform_default_instance_;
}  // namespace schemas
}  // namespace dai
static ::_pb::Metadata file_level_metadata_daischemas_2fFrameTransform_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_daischemas_2fFrameTransform_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_daischemas_2fFrameTransform_2eproto = nullptr;
const ::uint32_t TableStruct_daischemas_2fFrameTransform_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::dai::schemas::FrameTransform, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::dai::schemas::FrameTransform, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dai::schemas::FrameTransform, _impl_.timestamp_),
    PROTOBUF_FIELD_OFFSET(::dai::schemas::FrameTransform, _impl_.parent_frame_id_),
    PROTOBUF_FIELD_OFFSET(::dai::schemas::FrameTransform, _impl_.child_frame_id_),
    PROTOBUF_FIELD_OFFSET(::dai::schemas::FrameTransform, _impl_.translation_),
    PROTOBUF_FIELD_OFFSET(::dai::schemas::FrameTransform, _impl_.rotation_),
    0,
    ~0u,
    ~0u,
    1,
    2,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 13, -1, sizeof(::dai::schemas::FrameTransform)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::dai::schemas::_FrameTransform_default_instance_._instance,
};
const char descriptor_table_protodef_daischemas_2fFrameTransform_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\037daischemas/FrameTransform.proto\022\013dai.s"
    "chemas\032\033daischemas/Quaternion.proto\032\030dai"
    "schemas/Vector3.proto\032\037google/protobuf/t"
    "imestamp.proto\"\306\001\n\016FrameTransform\022-\n\ttim"
    "estamp\030\001 \001(\0132\032.google.protobuf.Timestamp"
    "\022\027\n\017parent_frame_id\030\002 \001(\t\022\026\n\016child_frame"
    "_id\030\003 \001(\t\022)\n\013translation\030\004 \001(\0132\024.dai.sch"
    "emas.Vector3\022)\n\010rotation\030\005 \001(\0132\027.dai.sch"
    "emas.Quaternionb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_daischemas_2fFrameTransform_2eproto_deps[3] =
    {
        &::descriptor_table_daischemas_2fQuaternion_2eproto,
        &::descriptor_table_daischemas_2fVector3_2eproto,
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_daischemas_2fFrameTransform_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_daischemas_2fFrameTransform_2eproto = {
    false,
    false,
    343,
    descriptor_table_protodef_daischemas_2fFrameTransform_2eproto,
    "daischemas/FrameTransform.proto",
    &descriptor_table_daischemas_2fFrameTransform_2eproto_once,
    descriptor_table_daischemas_2fFrameTransform_2eproto_deps,
    3,
    1,
    schemas,
    file_default_instances,
    TableStruct_daischemas_2fFrameTransform_2eproto::offsets,
    file_level_metadata_daischemas_2fFrameTransform_2eproto,
    file_level_enum_descriptors_daischemas_2fFrameTransform_2eproto,
    file_level_service_descriptors_daischemas_2fFrameTransform_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_daischemas_2fFrameTransform_2eproto_getter() {
  return &descriptor_table_daischemas_2fFrameTransform_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_daischemas_2fFrameTransform_2eproto(&descriptor_table_daischemas_2fFrameTransform_2eproto);
namespace dai {
namespace schemas {
// ===================================================================

class FrameTransform::_Internal {
 public:
  using HasBits = decltype(std::declval<FrameTransform>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_._has_bits_);
  static const ::google::protobuf::Timestamp& timestamp(const FrameTransform* msg);
  static void set_has_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::dai::schemas::Vector3& translation(const FrameTransform* msg);
  static void set_has_translation(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::dai::schemas::Quaternion& rotation(const FrameTransform* msg);
  static void set_has_rotation(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::google::protobuf::Timestamp& FrameTransform::_Internal::timestamp(const FrameTransform* msg) {
  return *msg->_impl_.timestamp_;
}
const ::dai::schemas::Vector3& FrameTransform::_Internal::translation(const FrameTransform* msg) {
  return *msg->_impl_.translation_;
}
const ::dai::schemas::Quaternion& FrameTransform::_Internal::rotation(const FrameTransform* msg) {
  return *msg->_impl_.rotation_;
}
void FrameTransform::clear_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void FrameTransform::clear_translation() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.translation_ != nullptr) _impl_.translation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void FrameTransform::clear_rotation() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.rotation_ != nullptr) _impl_.rotation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
FrameTransform::FrameTransform(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dai.schemas.FrameTransform)
}
inline PROTOBUF_NDEBUG_INLINE FrameTransform::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        parent_frame_id_(arena, from.parent_frame_id_),
        child_frame_id_(arena, from.child_frame_id_) {}

FrameTransform::FrameTransform(
    ::google::protobuf::Arena* arena,
    const FrameTransform& from)
    : ::google::protobuf::Message(arena) {
  FrameTransform* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.timestamp_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::protobuf::Timestamp>(arena, *from._impl_.timestamp_)
                : nullptr;
  _impl_.translation_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::dai::schemas::Vector3>(arena, *from._impl_.translation_)
                : nullptr;
  _impl_.rotation_ = (cached_has_bits & 0x00000004u)
                ? CreateMaybeMessage<::dai::schemas::Quaternion>(arena, *from._impl_.rotation_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:dai.schemas.FrameTransform)
}
inline PROTOBUF_NDEBUG_INLINE FrameTransform::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        parent_frame_id_(arena),
        child_frame_id_(arena) {}

inline void FrameTransform::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, rotation_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::rotation_));
}
FrameTransform::~FrameTransform() {
  // @@protoc_insertion_point(destructor:dai.schemas.FrameTransform)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FrameTransform::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.parent_frame_id_.Destroy();
  _impl_.child_frame_id_.Destroy();
  delete _impl_.timestamp_;
  delete _impl_.translation_;
  delete _impl_.rotation_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FrameTransform::Clear() {
// @@protoc_insertion_point(message_clear_start:dai.schemas.FrameTransform)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.parent_frame_id_.ClearToEmpty();
  _impl_.child_frame_id_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.timestamp_ != nullptr);
      _impl_.timestamp_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.translation_ != nullptr);
      _impl_.translation_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.rotation_ != nullptr);
      _impl_.rotation_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FrameTransform::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 3, 64, 2> FrameTransform::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_FrameTransform_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .google.protobuf.Timestamp timestamp = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.timestamp_)}},
    // string parent_frame_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.parent_frame_id_)}},
    // string child_frame_id = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.child_frame_id_)}},
    // .dai.schemas.Vector3 translation = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 1, PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.translation_)}},
    // .dai.schemas.Quaternion rotation = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 2, 2, PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.rotation_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Timestamp timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string parent_frame_id = 2;
    {PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.parent_frame_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string child_frame_id = 3;
    {PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.child_frame_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .dai.schemas.Vector3 translation = 4;
    {PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.translation_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .dai.schemas.Quaternion rotation = 5;
    {PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.rotation_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
    {::_pbi::TcParser::GetTable<::dai::schemas::Vector3>()},
    {::_pbi::TcParser::GetTable<::dai::schemas::Quaternion>()},
  }}, {{
    "\32\0\17\16\0\0\0\0"
    "dai.schemas.FrameTransform"
    "parent_frame_id"
    "child_frame_id"
  }},
};

::uint8_t* FrameTransform::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dai.schemas.FrameTransform)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Timestamp timestamp = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  // string parent_frame_id = 2;
  if (!this->_internal_parent_frame_id().empty()) {
    const std::string& _s = this->_internal_parent_frame_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dai.schemas.FrameTransform.parent_frame_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string child_frame_id = 3;
  if (!this->_internal_child_frame_id().empty()) {
    const std::string& _s = this->_internal_child_frame_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dai.schemas.FrameTransform.child_frame_id");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // .dai.schemas.Vector3 translation = 4;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, _Internal::translation(this),
        _Internal::translation(this).GetCachedSize(), target, stream);
  }

  // .dai.schemas.Quaternion rotation = 5;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, _Internal::rotation(this),
        _Internal::rotation(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dai.schemas.FrameTransform)
  return target;
}

::size_t FrameTransform::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dai.schemas.FrameTransform)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string parent_frame_id = 2;
  if (!this->_internal_parent_frame_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_parent_frame_id());
  }

  // string child_frame_id = 3;
  if (!this->_internal_child_frame_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_child_frame_id());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // .google.protobuf.Timestamp timestamp = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.timestamp_);
    }

    // .dai.schemas.Vector3 translation = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.translation_);
    }

    // .dai.schemas.Quaternion rotation = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.rotation_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FrameTransform::_class_data_ = {
    FrameTransform::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FrameTransform::GetClassData() const {
  return &_class_data_;
}

void FrameTransform::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FrameTransform*>(&to_msg);
  auto& from = static_cast<const FrameTransform&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dai.schemas.FrameTransform)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_parent_frame_id().empty()) {
    _this->_internal_set_parent_frame_id(from._internal_parent_frame_id());
  }
  if (!from._internal_child_frame_id().empty()) {
    _this->_internal_set_child_frame_id(from._internal_child_frame_id());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_timestamp()->::google::protobuf::Timestamp::MergeFrom(
          from._internal_timestamp());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_translation()->::dai::schemas::Vector3::MergeFrom(
          from._internal_translation());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_rotation()->::dai::schemas::Quaternion::MergeFrom(
          from._internal_rotation());
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FrameTransform::CopyFrom(const FrameTransform& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dai.schemas.FrameTransform)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FrameTransform::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FrameTransform::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FrameTransform::InternalSwap(FrameTransform* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.parent_frame_id_, &other->_impl_.parent_frame_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.child_frame_id_, &other->_impl_.child_frame_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.rotation_)
      + sizeof(FrameTransform::_impl_.rotation_)
      - PROTOBUF_FIELD_OFFSET(FrameTransform, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata FrameTransform::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_daischemas_2fFrameTransform_2eproto_getter, &descriptor_table_daischemas_2fFrameTransform_2eproto_once,
      file_level_metadata_daischemas_2fFrameTransform_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace schemas
}  // namespace dai
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
