// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: daischemas/FrameTransforms.proto

#include "daischemas/FrameTransforms.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace dai {
namespace schemas {

inline constexpr FrameTransforms::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : transforms_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FrameTransforms::FrameTransforms(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FrameTransformsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FrameTransformsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FrameTransformsDefaultTypeInternal() {}
  union {
    FrameTransforms _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FrameTransformsDefaultTypeInternal _FrameTransforms_default_instance_;
}  // namespace schemas
}  // namespace dai
static ::_pb::Metadata file_level_metadata_daischemas_2fFrameTransforms_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_daischemas_2fFrameTransforms_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_daischemas_2fFrameTransforms_2eproto = nullptr;
const ::uint32_t TableStruct_daischemas_2fFrameTransforms_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::dai::schemas::FrameTransforms, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dai::schemas::FrameTransforms, _impl_.transforms_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::dai::schemas::FrameTransforms)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::dai::schemas::_FrameTransforms_default_instance_._instance,
};
const char descriptor_table_protodef_daischemas_2fFrameTransforms_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n daischemas/FrameTransforms.proto\022\013dai."
    "schemas\032\037daischemas/FrameTransform.proto"
    "\"B\n\017FrameTransforms\022/\n\ntransforms\030\001 \003(\0132"
    "\033.dai.schemas.FrameTransformb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_daischemas_2fFrameTransforms_2eproto_deps[1] =
    {
        &::descriptor_table_daischemas_2fFrameTransform_2eproto,
};
static ::absl::once_flag descriptor_table_daischemas_2fFrameTransforms_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_daischemas_2fFrameTransforms_2eproto = {
    false,
    false,
    156,
    descriptor_table_protodef_daischemas_2fFrameTransforms_2eproto,
    "daischemas/FrameTransforms.proto",
    &descriptor_table_daischemas_2fFrameTransforms_2eproto_once,
    descriptor_table_daischemas_2fFrameTransforms_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_daischemas_2fFrameTransforms_2eproto::offsets,
    file_level_metadata_daischemas_2fFrameTransforms_2eproto,
    file_level_enum_descriptors_daischemas_2fFrameTransforms_2eproto,
    file_level_service_descriptors_daischemas_2fFrameTransforms_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_daischemas_2fFrameTransforms_2eproto_getter() {
  return &descriptor_table_daischemas_2fFrameTransforms_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_daischemas_2fFrameTransforms_2eproto(&descriptor_table_daischemas_2fFrameTransforms_2eproto);
namespace dai {
namespace schemas {
// ===================================================================

class FrameTransforms::_Internal {
 public:
};

void FrameTransforms::clear_transforms() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.transforms_.Clear();
}
FrameTransforms::FrameTransforms(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dai.schemas.FrameTransforms)
}
inline PROTOBUF_NDEBUG_INLINE FrameTransforms::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : transforms_{visibility, arena, from.transforms_},
        _cached_size_{0} {}

FrameTransforms::FrameTransforms(
    ::google::protobuf::Arena* arena,
    const FrameTransforms& from)
    : ::google::protobuf::Message(arena) {
  FrameTransforms* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:dai.schemas.FrameTransforms)
}
inline PROTOBUF_NDEBUG_INLINE FrameTransforms::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : transforms_{visibility, arena},
        _cached_size_{0} {}

inline void FrameTransforms::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FrameTransforms::~FrameTransforms() {
  // @@protoc_insertion_point(destructor:dai.schemas.FrameTransforms)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FrameTransforms::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FrameTransforms::Clear() {
// @@protoc_insertion_point(message_clear_start:dai.schemas.FrameTransforms)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.transforms_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FrameTransforms::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> FrameTransforms::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_FrameTransforms_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .dai.schemas.FrameTransform transforms = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FrameTransforms, _impl_.transforms_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .dai.schemas.FrameTransform transforms = 1;
    {PROTOBUF_FIELD_OFFSET(FrameTransforms, _impl_.transforms_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::dai::schemas::FrameTransform>()},
  }}, {{
  }},
};

::uint8_t* FrameTransforms::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dai.schemas.FrameTransforms)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .dai.schemas.FrameTransform transforms = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_transforms_size()); i < n; i++) {
    const auto& repfield = this->_internal_transforms().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dai.schemas.FrameTransforms)
  return target;
}

::size_t FrameTransforms::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dai.schemas.FrameTransforms)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .dai.schemas.FrameTransform transforms = 1;
  total_size += 1UL * this->_internal_transforms_size();
  for (const auto& msg : this->_internal_transforms()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FrameTransforms::_class_data_ = {
    FrameTransforms::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FrameTransforms::GetClassData() const {
  return &_class_data_;
}

void FrameTransforms::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FrameTransforms*>(&to_msg);
  auto& from = static_cast<const FrameTransforms&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dai.schemas.FrameTransforms)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_transforms()->MergeFrom(
      from._internal_transforms());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FrameTransforms::CopyFrom(const FrameTransforms& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dai.schemas.FrameTransforms)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FrameTransforms::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FrameTransforms::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FrameTransforms::InternalSwap(FrameTransforms* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.transforms_.InternalSwap(&other->_impl_.transforms_);
}

::google::protobuf::Metadata FrameTransforms::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_daischemas_2fFrameTransforms_2eproto_getter, &descriptor_table_daischemas_2fFrameTransforms_2eproto_once,
      file_level_metadata_daischemas_2fFrameTransforms_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace schemas
}  // namespace dai
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
