// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: daischemas/PackedElementField.proto

#include "daischemas/PackedElementField.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace dai {
namespace schemas {

inline constexpr PackedElementField::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        offset_{0u},
        type_{static_cast< ::dai::schemas::PackedElementField_NumericType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PackedElementField::PackedElementField(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PackedElementFieldDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PackedElementFieldDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PackedElementFieldDefaultTypeInternal() {}
  union {
    PackedElementField _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PackedElementFieldDefaultTypeInternal _PackedElementField_default_instance_;
}  // namespace schemas
}  // namespace dai
static ::_pb::Metadata file_level_metadata_daischemas_2fPackedElementField_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_daischemas_2fPackedElementField_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_daischemas_2fPackedElementField_2eproto = nullptr;
const ::uint32_t TableStruct_daischemas_2fPackedElementField_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::dai::schemas::PackedElementField, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dai::schemas::PackedElementField, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::dai::schemas::PackedElementField, _impl_.offset_),
    PROTOBUF_FIELD_OFFSET(::dai::schemas::PackedElementField, _impl_.type_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::dai::schemas::PackedElementField)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::dai::schemas::_PackedElementField_default_instance_._instance,
};
const char descriptor_table_protodef_daischemas_2fPackedElementField_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n#daischemas/PackedElementField.proto\022\013d"
    "ai.schemas\"\346\001\n\022PackedElementField\022\014\n\004nam"
    "e\030\001 \001(\t\022\016\n\006offset\030\002 \001(\007\0229\n\004type\030\003 \001(\0162+."
    "dai.schemas.PackedElementField.NumericTy"
    "pe\"w\n\013NumericType\022\013\n\007UNKNOWN\020\000\022\t\n\005UINT8\020"
    "\001\022\010\n\004INT8\020\002\022\n\n\006UINT16\020\003\022\t\n\005INT16\020\004\022\n\n\006UI"
    "NT32\020\005\022\t\n\005INT32\020\006\022\013\n\007FLOAT32\020\007\022\013\n\007FLOAT6"
    "4\020\010b\006proto3"
};
static ::absl::once_flag descriptor_table_daischemas_2fPackedElementField_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_daischemas_2fPackedElementField_2eproto = {
    false,
    false,
    291,
    descriptor_table_protodef_daischemas_2fPackedElementField_2eproto,
    "daischemas/PackedElementField.proto",
    &descriptor_table_daischemas_2fPackedElementField_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_daischemas_2fPackedElementField_2eproto::offsets,
    file_level_metadata_daischemas_2fPackedElementField_2eproto,
    file_level_enum_descriptors_daischemas_2fPackedElementField_2eproto,
    file_level_service_descriptors_daischemas_2fPackedElementField_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_daischemas_2fPackedElementField_2eproto_getter() {
  return &descriptor_table_daischemas_2fPackedElementField_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_daischemas_2fPackedElementField_2eproto(&descriptor_table_daischemas_2fPackedElementField_2eproto);
namespace dai {
namespace schemas {
const ::google::protobuf::EnumDescriptor* PackedElementField_NumericType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_daischemas_2fPackedElementField_2eproto);
  return file_level_enum_descriptors_daischemas_2fPackedElementField_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PackedElementField_NumericType_internal_data_[] = {
    589824u, 0u, };
bool PackedElementField_NumericType_IsValid(int value) {
  return 0 <= value && value <= 8;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr PackedElementField_NumericType PackedElementField::UNKNOWN;
constexpr PackedElementField_NumericType PackedElementField::UINT8;
constexpr PackedElementField_NumericType PackedElementField::INT8;
constexpr PackedElementField_NumericType PackedElementField::UINT16;
constexpr PackedElementField_NumericType PackedElementField::INT16;
constexpr PackedElementField_NumericType PackedElementField::UINT32;
constexpr PackedElementField_NumericType PackedElementField::INT32;
constexpr PackedElementField_NumericType PackedElementField::FLOAT32;
constexpr PackedElementField_NumericType PackedElementField::FLOAT64;
constexpr PackedElementField_NumericType PackedElementField::NumericType_MIN;
constexpr PackedElementField_NumericType PackedElementField::NumericType_MAX;
constexpr int PackedElementField::NumericType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class PackedElementField::_Internal {
 public:
};

PackedElementField::PackedElementField(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dai.schemas.PackedElementField)
}
inline PROTOBUF_NDEBUG_INLINE PackedElementField::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

PackedElementField::PackedElementField(
    ::google::protobuf::Arena* arena,
    const PackedElementField& from)
    : ::google::protobuf::Message(arena) {
  PackedElementField* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, offset_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, offset_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, offset_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:dai.schemas.PackedElementField)
}
inline PROTOBUF_NDEBUG_INLINE PackedElementField::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void PackedElementField::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, offset_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, offset_) +
               sizeof(Impl_::type_));
}
PackedElementField::~PackedElementField() {
  // @@protoc_insertion_point(destructor:dai.schemas.PackedElementField)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PackedElementField::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PackedElementField::Clear() {
// @@protoc_insertion_point(message_clear_start:dai.schemas.PackedElementField)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.offset_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.offset_)) + sizeof(_impl_.type_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PackedElementField::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 43, 2> PackedElementField::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PackedElementField_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PackedElementField, _impl_.name_)}},
    // fixed32 offset = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(PackedElementField, _impl_.offset_)}},
    // .dai.schemas.PackedElementField.NumericType type = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PackedElementField, _impl_.type_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(PackedElementField, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(PackedElementField, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // fixed32 offset = 2;
    {PROTOBUF_FIELD_OFFSET(PackedElementField, _impl_.offset_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFixed32)},
    // .dai.schemas.PackedElementField.NumericType type = 3;
    {PROTOBUF_FIELD_OFFSET(PackedElementField, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\36\4\0\0\0\0\0\0"
    "dai.schemas.PackedElementField"
    "name"
  }},
};

::uint8_t* PackedElementField::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dai.schemas.PackedElementField)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dai.schemas.PackedElementField.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // fixed32 offset = 2;
  if (this->_internal_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
        2, this->_internal_offset(), target);
  }

  // .dai.schemas.PackedElementField.NumericType type = 3;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dai.schemas.PackedElementField)
  return target;
}

::size_t PackedElementField::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dai.schemas.PackedElementField)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // fixed32 offset = 2;
  if (this->_internal_offset() != 0) {
    total_size += 5;
  }

  // .dai.schemas.PackedElementField.NumericType type = 3;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PackedElementField::_class_data_ = {
    PackedElementField::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PackedElementField::GetClassData() const {
  return &_class_data_;
}

void PackedElementField::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PackedElementField*>(&to_msg);
  auto& from = static_cast<const PackedElementField&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dai.schemas.PackedElementField)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_offset() != 0) {
    _this->_internal_set_offset(from._internal_offset());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PackedElementField::CopyFrom(const PackedElementField& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dai.schemas.PackedElementField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PackedElementField::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PackedElementField::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PackedElementField::InternalSwap(PackedElementField* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PackedElementField, _impl_.type_)
      + sizeof(PackedElementField::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(PackedElementField, _impl_.offset_)>(
          reinterpret_cast<char*>(&_impl_.offset_),
          reinterpret_cast<char*>(&other->_impl_.offset_));
}

::google::protobuf::Metadata PackedElementField::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_daischemas_2fPackedElementField_2eproto_getter, &descriptor_table_daischemas_2fPackedElementField_2eproto_once,
      file_level_metadata_daischemas_2fPackedElementField_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace schemas
}  // namespace dai
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
