// IWYU pragma: private, include "depthai/depthai.hpp"
#pragma once

// all the data types
#include "datatype/ADatatype.hpp"
#include "datatype/AprilTagConfig.hpp"
#include "datatype/AprilTags.hpp"
#include "datatype/BenchmarkReport.hpp"
#include "datatype/Buffer.hpp"
#include "datatype/CameraControl.hpp"
#include "datatype/EdgeDetectorConfig.hpp"
#include "datatype/EncodedFrame.hpp"
#include "datatype/FeatureTrackerConfig.hpp"
#include "datatype/IMUData.hpp"
#include "datatype/ImageManipConfig.hpp"
#include "datatype/ImageManipConfigV2.hpp"
#include "datatype/ImgDetections.hpp"
#include "datatype/ImgFrame.hpp"
#include "datatype/MessageGroup.hpp"
#include "datatype/NNData.hpp"
#include "datatype/PointCloudConfig.hpp"
#include "datatype/PointCloudData.hpp"
#include "datatype/SpatialImgDetections.hpp"
#include "datatype/SpatialLocationCalculatorConfig.hpp"
#include "datatype/SpatialLocationCalculatorData.hpp"
#include "datatype/StereoDepthConfig.hpp"
#include "datatype/SystemInformation.hpp"
#include "datatype/SystemInformationS3.hpp"
#include "datatype/ToFConfig.hpp"
#include "datatype/TrackedFeatures.hpp"
#include "datatype/Tracklets.hpp"
