// IWYU pragma: private, include "depthai/depthai.hpp"
#pragma once

// all the data types
#include "datatype/ADatatype.hpp"
#include "datatype/AprilTagConfig.hpp"
#include "datatype/AprilTags.hpp"
#include "datatype/BenchmarkReport.hpp"
#include "datatype/Buffer.hpp"
#include "datatype/CameraControl.hpp"
#include "datatype/EdgeDetectorConfig.hpp"
#include "datatype/EncodedFrame.hpp"
#include "datatype/FeatureTrackerConfig.hpp"
#include "datatype/IMUData.hpp"
#include "datatype/ImageManipConfig.hpp"
#include "datatype/ImgDetections.hpp"
#include "datatype/ImgDetectionsT.hpp"
#include "datatype/ImgFrame.hpp"
#include "datatype/MessageGroup.hpp"
#include "datatype/NNData.hpp"
#include "datatype/NeuralDepthConfig.hpp"
#include "datatype/PointCloudConfig.hpp"
#include "datatype/PointCloudData.hpp"
#include "datatype/RGBDData.hpp"
#include "datatype/SpatialImgDetections.hpp"
#include "datatype/SpatialLocationCalculatorConfig.hpp"
#include "datatype/SpatialLocationCalculatorData.hpp"
#include "datatype/StereoDepthConfig.hpp"
#include "datatype/SystemInformation.hpp"
#include "datatype/SystemInformationS3.hpp"
#include "datatype/ThermalConfig.hpp"
#include "datatype/ToFConfig.hpp"
#include "datatype/TrackedFeatures.hpp"
#include "datatype/Tracklets.hpp"
#include "datatype/TransformData.hpp"
#ifdef DEPTHAI_HAVE_DYNAMIC_CALIBRATION_SUPPORT
    #include "datatype/DynamicCalibrationControl.hpp"
    #include "datatype/DynamicCalibrationResults.hpp"
#endif
#include "datatype/VppConfig.hpp"
